### ISSUE TITLE
Row "Highlight" rendering is not correct (according to how trackers generally work)

### ISSUE THREAD

**Issue by jaygarcia** [moduscreate/trackerEditor#12]
The original author highlights every 4th row to emulate trackers. It's wrong because it should be the first row and every 5th row thereafter.

![See this image](https://dexp.in/images/other/schi/s02.png)

**Comment by vadimpopa** [comment]
@jaygarcia Above screenshot is how it should be ? Seems to be the same as it is now.

**Comment by jaygarcia** [comment]
It should highlight:

Row 1 and (4+1 there after).
Today it's

_ _ _ 4 _ _ _ 8 _ _ _ 12 _ _ _ 16 <-- this is wrong.

it should be:

1 _ _ _ 5 _ _ _ 9 _ _ _ 13 _ _ _ 17

Does that make sense?

**Comment by jaygarcia** [comment]
What makes it "off" is that the tracker (above) has a row zero. 

Every "highlight" is a division of 4, but the math is off.

This is an image of Reason, a pro music production tool.  Please note the segment mathematics.

![2017-11-15_11-08-47](https://user-images.githubusercontent.com/180031/32846503-6a50aba0-c9f5-11e7-86ee-f18f174d3e48.png)

**Comment by jaygarcia** [comment]
Yes! or, let's start with zero base. 0 _ _ _ 4 _ _ _ _ 16 ,etc. If you can, plz pad 0, 4 with a zero. so "00", "04" to keep consistent formatting

**Comment by vadimpopa** [comment]
If we start from 0 there always will be the last one off, for the screenshot case, there are only 8 notes, but we need to have 9 notes, in order to have the 8'th row displayed

<img width="752" alt="screen shot 2017-11-15 at 6 34 49 pm" src="https://user-images.githubusercontent.com/3592131/32847896-dc82c274-ca33-11e7-83a2-1a37600b6def.png">

**Comment by vadimpopa** [comment]
Unless we add one more note, which I'm not sure what this means :D for the track

**Comment by vadimpopa** [comment]
Yeah, think I got it, so I just added one more tick to the default new track (they were 8, now will be 9), and now we have default displayed ok, in other case, depends on the loaded track, or how many ticks the users has applied.

<img width="764" alt="screen shot 2017-11-15 at 6 43 28 pm" src="https://user-images.githubusercontent.com/3592131/32848390-0a959c58-ca35-11e7-850b-153f52f392c5.png">

**Comment by jaygarcia** [comment]
This is great!! Thank you very much @vadimpopa
