### ISSUE TITLE
Add confirmation on "delete" of a track

### ISSUE THREAD

**Issue by moduscreate** [moduscreate/trackerEditor#2]

**Comment by slemmon** [comment]
PR: https://github.com/moduscreate/trackerEditor/pull/15

**Comment by slemmon** [comment]
@jaygarcia With the merge of https://github.com/moduscreate/trackerEditor/pull/15 this issue can be closed, yeah?

**Comment by jaygarcia** [comment]
Yes sir. Thanks for the reminder. =D
