### ISSUE TITLE
Pattern editor is misaligned due to the scroll bar of Chrome (on mac)

### ISSUE THREAD

**Issue by moduscreate** [moduscreate/trackerEditor#8]

**Comment by vadimpopa** [comment]
@jaygarcia could you please post here a screenshot, I'm not sure where's the pattern editor. I may assume is this one:

<img width="741" alt="screen shot 2017-11-13 at 8 06 33 pm" src="https://user-images.githubusercontent.com/3592131/32741307-7b46633e-c8ae-11e7-96b2-ea28beb0d4b0.png">

**Comment by jaygarcia** [comment]
@vadimpopa yes. 

The last key is missing due to the scroll bar.

**Comment by vadimpopa** [comment]
Fixed:

<img width="900" alt="screen shot 2017-11-13 at 8 58 48 pm" src="https://user-images.githubusercontent.com/3592131/32743635-a657aec8-c8b5-11e7-816d-947c8d718f5a.png">

**Comment by jaygarcia** [comment]
This is awesome! Does it persist if you change the row count > 16? :D

**Comment by vadimpopa** [comment]
Seems so :)

<img width="772" alt="screen shot 2017-11-13 at 9 13 02 pm" src="https://user-images.githubusercontent.com/3592131/32744225-7deddfc8-c8b7-11e7-84a4-5753404b7634.png">

**Comment by jaygarcia** [comment]
Thank you for the fix!!
